# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

In [3]:
df=pd.read_csv("cars1.csv")
df
de=pd.read_csv("cars2.csv")
de

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,33.0,4,91,53,1795,17.4,76,3,honda civic
1,20.0,6,225,100,3651,17.7,76,1,dodge aspen se
2,18.0,6,250,78,3574,21.0,76,1,ford granada ghia
3,18.5,6,250,110,3645,16.2,76,1,pontiac ventura sj
4,17.5,6,258,95,3193,17.8,76,1,amc pacer d/l
...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
196,44.0,4,97,52,2130,24.6,82,2,vw pickup
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage
198,28.0,4,120,79,2625,18.6,82,1,ford ranger
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10

   ### Step 3. Assign each to a variable called cars1 and cars2

In [ ]:
car1=pd.read_csv("cars1.csv")
car1
car2=pd.read_csv("cars2.csv")
car2

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,24.0,6,200,81,3012,17.6,76,1,ford maverick,NaN,NaN,NaN,NaN,NaN
194,22.5,6,232,90,3085,17.6,76,1,amc hornet,NaN,NaN,NaN,NaN,NaN
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette,NaN,NaN,NaN,NaN,NaN
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody,NaN,NaN,NaN,NaN,NaN
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit,NaN,NaN,NaN,NaN,NaN

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [12]:
car1=pd.read_csv("cars1.csv")
new_car=car1.drop(["Unnamed: 9","Unnamed: 10","Unnamed: 11","Unnamed: 12","Unnamed: 13"],axis=1)
new_car

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
193,24.0,6,200,81,3012,17.6,76,1,ford maverick
194,22.5,6,232,90,3085,17.6,76,1,amc hornet
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit

### Step 5. What is the number of observations in each dataset?

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [15]:
cars=pd.concat([df,de],ignore_index=True)
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,NaN,NaN,NaN,NaN,NaN
394,44.0,4,97,52,2130,24.6,82,2,vw pickup,NaN,NaN,NaN,NaN,NaN
395,32.0,4,135,84,2295,11.6,82,1,dodge rampage,NaN,NaN,NaN,NaN,NaN
396,28.0,4,120,79,2625,18.6,82,1,ford ranger,NaN,NaN,NaN,NaN,NaN
397,31.0,4,119,82,2720,19.4,82,1,chevy s-10,NaN,NaN,NaN,NaN,NaN

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [29]:
import numpy as np
carr=np.random.randint(15000,73000,size=len(cars))
carr

array([63727, 19786, 15094, 40970, 20267, 21581, 62022, 44299, 68751,
       36403, 18834, 42112, 42961, 28855, 47717, 21324, 37089, 17270,
       67058, 41316, 17042, 50543, 50429, 72921, 56286, 22556, 40870,
       65477, 17045, 65461, 45294, 42821, 53125, 53821, 37119, 45633,
       32713, 71967, 55883, 43488, 48962, 16001, 59077, 46795, 63417,
       27540, 65327, 32179, 36769, 49691, 66639, 71629, 59089, 70625,
       17369, 67664, 36047, 43873, 37785, 62201, 32946, 27232, 71330,
       45626, 59104, 67893, 63973, 16790, 60775, 56071, 15326, 40830,
       20001, 29464, 56717, 35114, 31924, 20669, 42075, 22350, 62662,
       53764, 48337, 21511, 32516, 50985, 72178, 61086, 15512, 34694,
       62242, 35801, 26050, 33419, 56740, 49285, 16508, 47522, 21630,
       16236, 21271, 39873, 48640, 43984, 55630, 53150, 71208, 17503,
       66781, 31949, 47500, 16709, 53656, 50710, 18425, 32459, 65917,
       64157, 70890, 63938, 23032, 71257, 30757, 40536, 60157, 53148,
       18992, 43485, 57669, 50980, 68368, 66845, 24825, 38392, 23192,
       41179, 23798, 59994, 59461, 60238, 72397, 51244, 30436, 58459,
       65085, 60780, 62535, 71029, 32118, 27600, 38687, 27683, 63345,
       36362, 22921, 30906, 48217, 36117, 33203, 60227, 40669, 38529,
       18825, 42180, 36719, 56419, 36473, 59146, 50469, 53345, 37284,
       25689, 70369, 68627, 44238, 40683, 68921, 28661, 46256, 18598,
       62538, 20777, 44019, 37528, 31421, 40537, 41761, 47461, 69171,
       44170, 26947, 34795, 18576, 44315, 56916, 19374, 38480, 65016,
       52180, 59757, 37107, 16365, 60268, 60107, 29300, 64191, 68349,
       23533, 60560, 56499, 69253, 54414, 46782, 62346, 22387, 43151,
       49191, 16278, 56345, 60066, 30198, 71892, 25594, 71230, 42817,
       17535, 23579, 26226, 32199, 27640, 37010, 67570, 51351, 53709,
       25019, 71853, 57838, 37107, 48259, 51090, 48873, 25536, 28944,
       66752, 21798, 24627, 62835, 68165, 71254, 36290, 22060, 17653,
       49669, 64891, 21239, 17465, 32887, 68531, 42308, 32924, 31433,
       33957, 42211, 40961, 29419, 51509, 60210, 60494, 32105, 29887,
       65491, 70641, 71005, 46890, 55688, 52532, 41952, 41434, 41224,
       26614, 41133, 38474, 26442, 26880, 20910, 49395, 57486, 36069,
       64838, 38857, 27633, 50591, 48957, 52153, 61810, 60885, 56184,
       35685, 72966, 56721, 20748, 57003, 72946, 38521, 45294, 29485,
       67808, 62338, 26034, 17480, 67461, 53380, 60415, 43405, 40906,
       58390, 33240, 44977, 40933, 53457, 59520, 64942, 38460, 57392,
       60714, 20768, 62521, 59286, 22579, 59512, 27466, 40671, 51785,
       36462, 26846, 30764, 69904, 66582, 21028, 37523, 16473, 24342,
       53646, 65906, 16988, 51805, 25168, 43268, 65181, 61060, 35480,
       60516, 41672, 60153, 64259, 41730, 52184, 59051, 65890, 27378,
       41000, 37203, 54393, 69523, 42126, 33989, 38304, 58819, 69262,
       64259, 61107, 49944, 16067, 37502, 63264, 53233, 68307, 27439,
       70365, 41516, 57634, 19254, 66080, 15457, 23708, 63326, 16450,
       25410, 23705, 22375, 48053, 31745, 42569, 39282, 44058, 57598,
       21132, 66717], dtype=int32)

### Step 8. Add the column owners to cars

In [27]:
cars.insert(0,"owner",[])

ValueError: Length of values (0) does not match length of index (398)